### ISSUE TITLE
Allow users to abort game

### ISSUE THREAD

**Issue by rspilker** [bennorichters/bnoggles#8]
If there is time remaining, but I cannot think of any words anymore, I'd like to be able to go to the results screen without having to wait until time is up.

**Comment by bennorichters** [comment]
There already is! The stop button on the "AppBar" in the top right corner. But apparently (because of this issue) that is not obvious enough. Might it be that the "debug" ribbon next to it hides this option? Would it help if the color is red? Or it just needs to be more in your face? Open for suggestions.

**Comment by rspilker** [comment]
The debug banner doesn't help, but I think making it red would be an improvement.

**Comment by rspilker** [comment]
Pull request #16 makes the stop button red

**Comment by rspilker** [comment]
I think that the red button is good enough. I close the issue. Let's await other users' feedback to see if they agree.
